/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary-fixed-dim': '#c3c7cb',
        'on-tertiary': '#ffffff',
        'outline-variant': '#c3c6d7',
        'tertiary-container': '#656d84',
        'on-surface': '#0b1c30',
        'inverse-on-surface': '#eaf1ff',
        'on-primary': '#ffffff',
        error: '#ba1a1a',
        'on-secondary': '#ffffff',
        'surface-container': '#e5eeff',
        'surface-variant': '#d3e4fe',
        'on-tertiary-fixed': '#131b2e',
        'surface-container-highest': '#d3e4fe',
        'on-primary-container': '#eeefff',
        background: '#f8f9ff',
        'secondary-fixed': '#dfe3e7',
        'surface-bright': '#f8f9ff',
        'surface-container-high': '#dce9ff',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'primary-fixed-dim': '#b4c5ff',
        'on-primary-fixed': '#00174b',
        primary: '#004ac6',
        'primary-container': '#2563eb',
        'on-surface-variant': '#434655',
        'on-tertiary-container': '#eef0ff',
        'on-primary-fixed-variant': '#003ea8',
        'on-secondary-container': '#5e6367',
        secondary: '#5a5f62',
        'on-background': '#0b1c30',
        'surface-tint': '#0053db',
        'tertiary-fixed-dim': '#bec6e0',
        'primary-fixed': '#dbe1ff',
        'inverse-primary': '#b4c5ff',
        'surface-dim': '#cbdbf5',
        'on-secondary-fixed-variant': '#43474b',
        tertiary: '#4d556b',
        'on-tertiary-fixed-variant': '#3f465c',
        'surface-container-low': '#eff4ff',
        'tertiary-fixed': '#dae2fd',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed': '#171c1f',
        'inverse-surface': '#213145',
        surface: '#f8f9ff',
        'secondary-container': '#dce0e4',
        'error-container': '#ffdad6',
        outline: '#737686',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        sm: '8px',
        base: '4px',
        xs: '4px',
        md: '16px',
        '3xl': '64px',
        lg: '24px',
        xl: '32px',
        '2xl': '48px',
      },
      fontFamily: {
        display: ['Geist', 'system-ui', '-apple-system', 'Segoe UI', 'Roboto', 'sans-serif'],
        body: ['Geist', 'system-ui', '-apple-system', 'Segoe UI', 'Roboto', 'sans-serif'],
        label: ['Geist', 'system-ui', '-apple-system', 'Segoe UI', 'Roboto', 'sans-serif'],
        headline: ['Geist', 'system-ui', '-apple-system', 'Segoe UI', 'Roboto', 'sans-serif'],
        arabic: ['Cairo', 'system-ui', '-apple-system', 'sans-serif'],
      },
      fontSize: {
        display: ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'display-mobile': ['36px', { lineHeight: '42px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
